### ISSUE TITLE
Contact info to get WS_SECRET in .env file.

### ISSUE THREAD

**Issue by chrisli30** [tomochain/tomochain-testnet#1]
Hi there,

I'm interested in setting up a node on testnet. In your README.md you didn't specify how to contact you so I'm creating an issue here. Could you update your contact info on README.md?

Could you send me info of WS_SERECT to chris.li.2046@gmail.com?

Thanks!

Chris

**Comment by thanhson1085** [comment]
Join our gitter https://gitter.im/TOMOCOIN/Lobby to get the support. 
Thank you.
