### ISSUE TITLE
Try to setup a node to connect the testnet

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomochain-testnet#14]
Follow the tutorial in readme file, you should setup a node in local. After that, using a wallet and send/receive $TOMO.

If there is any problem, report it here.

**Comment by benjyz** [comment]
would like to try. I need WS_SECRET?

**Comment by thanhson1085** [comment]
Remove `localtime` lines in dockercompose file on Mac Environment

**Comment by benjyz** [comment]
works fine now. can add some more docs if needed

the explorer works too not but not sure how to connect to testnet, requires maybe changes here

https://github.com/tomochain/tomo-explorer/blob/master/server/.env.example
https://github.com/tomochain/tomo-explorer/blob/master/docker-compose-prod.yml#L36

**Comment by thanhson1085** [comment]
We are updating readme file of tomoscan (tomo explorer)

**Comment by etienne-napoleone** [comment]
@benjyz We are currently reworking how we deploy and maintain each services. I will update this issue with more infos once it's ready

**Comment by etienne-napoleone** [comment]
@benjyz you might give a try to run a msternode using https://github.com/tomochain/tmn and the instructions here: https://docs.tomochain.com/get-started/run-node/

Closing this issue
