### ISSUE TITLE
Error path /etc/localtime with docker on Mac Os X

### ISSUE THREAD

**Issue by chris-tn** [tomochain/tomochain-testnet#2]
ERROR: for tomochaintestnet_vet_1  Cannot start service vet: b'Mounts denied: \r\nThe path /etc/localtime\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for vet  Cannot start service vet: b'Mounts denied: \r\nThe path /etc/localtime\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.

**Comment by thanhson1085** [comment]
Try to remove `- "/etc/localtime:/etc/localtime:ro"` lines `docker-stack.yml` file before running `docker-compose up` command.

On Mac OS, `/etc/localtime` file doesn't exists.

**Comment by chrisli30** [comment]
Thanks Nguyen. I had the same problem on Mac and your solution works. One thing to note though, /etc/localtime needs to removed from both vet and netapis volumes, and since netapis volumes will be empty the "volumes:" key should be removed too.
